name: SwishPlugin
version: '${project.version}'
main: io.github.musikhjalpen2022.swishplugin.SwishPlugin
api-version: 1.18
authors: [ Rasmus, Anton ]
description: This is a plugin for Swish integration
commands:
  swish:
    description: Make a swish request for the given phone number
    usage: /swish 1234567890 123
  donate:
    description: Make a fake donation with player username and amount
    default: op
  checkpoint:
    description: Set or teleport to checkpoint
  parkour:
    description: Set or remove trial from player
    default: op