name: SwishPlugin
version: '${project.version}'
main: io.github.musikhjalpen2022.swishplugin.SwishPlugin
api-version: 1.18
authors: [ Rasmus, Anton ]
description: This is a plugin for Swish integration
commands:
  swish:
    description: Make a swish request for the given phone number
  donate:
    description: Make a fake donation with player username and amount
